# Configuration file 
# config.yaml
data:
  train_path: "data/train.csv"
  test_path: "data/test.csv"
  val_path: "data/validation.csv"
  batch_size: 32
  num_workers: 4

model:
  input_size: 21  # One-hot encoding of 20 amino acids + 1 padding
  hidden_size: 128
  num_layers: 2
  output_size: 1  # Binary classification

training:
  num_epochs: 20
  learning_rate: 0.001
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"
