# Description: Configuration file for the model training

data:
  train_path: "data/"
  test_path: "data/"
  batch_size: 32
  num_workers: 4

model:
  input_size: 21  # 20 for one-hot encoded amino acid + 1 for RSA
  hidden_size: 64
  num_layers: 2
  output_size: 1  # Binary classification

training:
  num_epochs: 20
  learning_rate: 0.001
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"